[tool.poetry]
name = "pinto-conda-example"
version = "0.0.1"
description = "Dummy Pinto Conda project example"
authors = ["Alec Gunny <alec.gunny@gmail.com>"]

[tool.poetry.scripts]
testme = "pinto_conda_example:main"

[tool.poetry.dependencies]
pip_install_test = "^0.5"
